FROM node:24-alpine

RUN apk upgrade --no-cache

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev && \
	rm -rf /usr/local/lib/node_modules/npm \
		   /usr/local/lib/node_modules/corepack \
		   /usr/local/bin/npm \
		   /usr/local/bin/npx \
		   /usr/local/bin/corepack

COPY worker ./worker

EXPOSE 3001

CMD ["node", "worker/worker.js"]
